#SPDX-License-Identifier: MIT-0
---
- name: Restart PostgreSQL
  service:
    name: "{{ postgresql_service }}"
    state: restarted

- name: Create a new database
  community.postgresql.postgresql_db:
    name: mydb
    comment: My test DB
  
# - name: Create a new database
#   postgresql_db:
#     name: mydb
#     encoding: UTF8
#     lc_collate: en_US.UTF-8
#     lc_ctype: en_US.UTF-8

- name: Create a new PostgreSQL user
  postgresql_user:
    db: mydb
    name: myuser
    password: mypassword
    priv: ALL
    state: present
