---
# tasks file for roles/aws-cli
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes
- name: Install required packages for AWS CLI
  ansible.builtin.apt:
    name:
     - curl
     - unzip
    state: present
- name: Download AWS CLI installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: Unzip AWS CLI installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Run AWS CLI installer
  command: "/tmp/aws/install --update"

- name: Verify AWS CLI installation
  command: "aws --version"
  register: aws_cli_version

- name: Display AWS CLI version
  debug:
    msg: "{{ aws_cli_version.stdout }}"