---
- name: playbook for user creation
  hosts: all
  become: true
  gather_facts: false
  vars:
    user: aman
  tasks:
    - name: creating a public folder
      ansible.builtin.file:
        name: /app/betternight/public
        state: directory
        mode: 0777
        

    - name: create a user {{ user }}} 
      ansible.builtin.user:
        name: "{{ user }}"
        state: present
        shell: /bin/bash
        password: "{{ 'Aman#123' | password_hash('sha512') }}"
        groups: sudo, adm, ubuntu
        create_home: yes