---
- name: Use Ansible Facts
  hosts: all
  become: yes

  tasks:
    - name: Print OS Distribution
      debug:
        msg: "This server is running {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Print IP Address
      debug:
        msg: "The server's primary IP is {{ ansible_default_ipv4.address }}"
