#SPDX-License-Identifier: MIT-0
---
- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
  notify:
    - start apache service
    - restart apache service
